### ISSUE TITLE
[EPIC] Define chart tests for kube-monitoring to be executed

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#141]
## Context 

Currently, the Greenhouse HelmController only checks if the version of a Plugin has been successfully installed/updated. However, no additional checks are made to ensure that the components of the Helm release work as expected.
Using [Chart Tests](https://helm.sh/docs/topics/chart_tests/), it is possible to perform a series of tests after a Helm install/upgrade has been executed to check whether the deployed components are working as intended.

## Tasks

- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/217
- [x] https://github.com/cloudoperators/greenhouse-extensions/pull/259
- [ ] https://github.com/cloudoperators/greenhouse/pull/401
Ref: 

- https://github.com/cloudoperators/greenhouse/issues/106
- https://github.com/cloudoperators/greenhouse/issues/185

**Comment by richardtief** [comment]
More refs: 

- https://github.com/sapcc/helm-charts/blob/master/common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
-
