### ISSUE TITLE
[EPIC] Kubernetes monitoring expansion stage 1

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#143]
## Context

Umbrella issue for tracking efforts on Kubernetes monitoring plugin expansion stage 1. 

The Greenhouse catalog offers a plugin that install a collection of Kubernetes manifests and Prometheus rules. They are combined with documentation and scripts to provide easy-to-use end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.

## Tickets

- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/120
- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/127
- [x]  https://github.com/cloudoperators/greenhouse-extensions/issues/141
