### ISSUE TITLE
[EPIC] OpenTelemetry essentials for logs

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#18]
## Context

Umbrella issue for evaluating OpenTelemetry to collect and process logs. 

The Greenhouse catalogue provides plugins that install a well-defined log infrastructure. These are combined with documentation and scripts to enable user-friendly end-to-end monitoring of Kubernetes clusters with Opensearch using the OpenTelemetry standard. This issue describes the first steps for obtaining logs via the Opentelemetry collector.

**Data Flow**:

![image](https://github.com/cloudoperators/greenhouse-extensions/assets/4355027/91f4919b-1e7c-4629-ac87-ec3d1d65c49c)

## Tickets

- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/34
- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/171
- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/148

## Acceptance criteria
1. Proof of concept for logs with OTEL
2. Decentralized architecture
3. Consider SAP Converged Cloud best practices
4. Plugin tests
5. Documentation
