### ISSUE TITLE
[alerts] Create chart integration tests

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#359]
## Context

The alerts plugin deploys the Prometheus Alertmanager and its configuration. It also serves as a backend for the Supernova UI, which expects a valid, accessible API endpoint. The chart tests should therefore cover the following areas: 

## Tasks
- [x] The prometheus-operator CRDs are installed (if the alerts plugin manages them)
- [x] All hooks are created (Issuer, Certificate, Secrets) 
   - https://github.com/cloudoperators/greenhouse-extensions/blob/main/alerts/charts/templates/ca-secret-issuer-cert.yaml
- [x] The Alertmanager pod is operational
- [x] The Alertmanager config is valid. Reflected on the status type "Reconciled". (alertmanager object `.status`)
   ```bash
      ⎈ k get alertmanager -o yaml | yq .items[].status.conditions                 
                                                                          
          - lastTransitionTime: "2024-05-06T19:29:48Z"
            message: ""
            observedGeneration: 1
            reason: ""
            status: "True"
            type: Available
          - lastTransitionTime: "2024-05-06T19:29:48Z"
            message: 'provision alertmanager configuration: failed to initialize from secret: group_interval cannot be zero'
            observedGeneration: 1
            reason: ReconciliationFailed
            status: "False"
            type: Reconciled
   ```
   ---
   ```bash
     ⎈ k get alertmanager -o yaml | yq .items[].status.conditions[].status     
                                                                        
          True
          False
   ```
- [ ] The host created for Supernova UI is reachable and delivers an `HTTP 200` code on `/api/v2/alerts`
   - use the host from Ingress
   - the Secret `tls-{{ $.Release.Namespace }}-prometheus-auth` can be used to authenticate
   - prior art: https://github.com/cloudoperators/greenhouse-extensions/blob/3cf431b66a29c5ff2bff39ee89d4844a3a99a6f8/plutono/charts/templates/tests/test-configmap.yaml#L17-L22

**Comment by ibakshay** [comment]
Hi @richardtief,  @viennaa, 
> 1. All hooks are created (Issuer, Certificate, Secrets)
> 2. The host created for Supernova UI is reachable and delivers an HTTP 200 code on /api/v2/alerts

These two tests can only be performed when `.Values.alerts.alertmanager.ingress.enabled` is set to **true**. I observed that it is set to **false** by default. https://github.com/cloudoperators/greenhouse-extensions/blob/main/alerts/charts/values.yaml#L170-L171
From my investigation, it seems there's no way to override the values.yaml file during the helm chart test. Do you have any suggestions on how to approach these two test cases? :)

**Comment by richardtief** [comment]
You can switch the tests on and off in the helm template. For example, like this: 
https://github.com/cloudoperators/greenhouse-extensions/blob/f7c6f0e26a987121e55569d289c5c677f17d8701/opentelemetry/chart/templates/tests/test-opentelemetry-config.yaml#L33
