### ISSUE TITLE
[EPIC] Plutono Replacement: Evaluation of Perses

### ISSUE THREAD

**Issue by ibakshay** [cloudoperators/greenhouse-extensions#417]
## Context

Currently, We are using [Plutono](https://github.com/credativ/plutono) a fork of `Grafana` for all our dashboards and visualisations. However, Plutono is in maintenance-only mode, making it a non-viable long-term solution. We need to identify and adopt a suitable alternative that fulfils our requirements.

### Requirements for a New Tool
- Open-source with an Apache 2.0 license
- Ability to connect to `Prometheus` and `Thanos` data sources
- Support for creating custom dashboards
- Management of dashboards using a Dashboard as Code approach

The alternative tool that we are considering is [perses](https://perses.dev/). Perses which is a CNCF sandbox project shows strong potential as a viable replacement for Grafana/Plutono. Perses is currently in the early stages of active development. 

This tools satisfies most of our requirements. So, we have to evaluate this tool by doing a POC. The POC should cover the following:

### Acceptance Criteria:

- [x] Test `perses` in our test sandbox environment.
  - [x] #418
  - [x] #419
  - [x] #420
- [ ] dashboards
  - [x] create a custom dashboard using `perses`.
  - [x] #480
      - [ ] Migration tooling provided by Perses for latest Grafana. Dashboards created with Plutono, which is based on older  Grafana version, doesn’t work out of the box. Manual work required.
- [x] Try out the Perses CLI 
- [x] #491
- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/540
- [x] community work
  - [x] report issues upstream
  - [x] critical issues might be tackled with upstream contribution

**Comment by richardtief** [comment]
Done. #539
