### ISSUE TITLE
[OpenSearch]  Implement OpenSearch monitoring, rollout with Kubernetes Operator/Umbrella chart.

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#425]
#### Acceptance criteria:

- [ ] OpenSearch database metrics provided via Prometheus endpoint
- [ ] Prometheus PodMonitor
- [ ] Rollout of Plutono dashboards for OpenSearch clusters
- [ ] Alerts for cluster yellow/red and disk issues
- [ ] Documents for resolving all cluster alerts
