### ISSUE TITLE
[EPIC] Multiple Prometheus installations in a cluster

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#442]
## Context

Umbrella issue for tracking efforts on Kubernetes monitoring plugin expansion stage 2. 

The Greenhouse catalog offers a plugin that install Kubernetes monitoring tools and the [kubernetes-operations](https://github.com/cloudoperators/kubernetes-operations/tree/main) bundle. They are combined with documentation and scripts to provide easy-to-use end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.

## Tickets

- [ ] https://github.com/cloudoperators/greenhouse-extensions/issues/140
- [x] https://github.com/cloudoperators/greenhouse-extensions/issues/142
- [ ] Documentation, lots of documentation
