### ISSUE TITLE
[perses] Create an Beta plugin

### ISSUE THREAD

**Issue by ibakshay** [cloudoperators/greenhouse-extensions#491]
### TODOs: 

- [x] Contribute to the upstream Perses helm Chart so that it can be used as a Chart dependency
   - https://github.com/perses/helm-charts/pull/37#event-15299963628
- [x] Create a Perses plugin 
  - [x]  The plugin should have all the default migrated plutono dashboards in the form of configmap (kubenetes, prometheus)
