### ISSUE TITLE
[EPIC] Plugin for Audit-Logs using OpenTelemetry

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#544]
## Context 
Besides customer-logs and operational logs, we agreed on creating a separate Greenhouse Plugin for shipping audit-logs (based on OpenTelemetry) in order to maintain security, ensure compliance, and improving system management/maintainability. This ticket should track the progress for the first version of a audit-logging plugin. 

## Acceptance Criteria 

- [ ] Define what kind of logs are required for audit-logging (also check what we already have available in Greenhouse)
- [ ] Define standards for our landscape (align with colleagues e.g. [here](https://github.com/open-telemetry/community/pull/2409))
- [ ] Define architecture: e.g. same as the OpenTelemetry plugin with operator and collectors on each node?
- [ ] Define necessary receivers, processors and exporters
- [x] Build first version of Plugin including PluginDefinition with custom fields
